MAGIC_BYTES = b"ORIPICS!"

OFFSET_MAGIC = 0
OFFSET_VERSION = 8
OFFSET_SALT_ID = 10
OFFSET_LENGTH = 12
OFFSET_TIMESTAMP = 16
OFFSET_WIDTH = 31
OFFSET_HEIGHT = 35
OFFSET_FINAL_HASH = 39

META_LENGTH = 39
HASH_LENGTH = 32
PAYLOAD_LENGTH = META_LENGTH + HASH_LENGTH

TIMESTAMP_LENGTH = 15
UPLOAD_TYPE_PREFIXES = ("F", "P", "C")
